### ISSUE TITLE
Active node中看不到其他设备，求助

### ISSUE THREAD

**Issue by stephensund** [ntlf9t/luci-app-easymesh#14]
我是两台竞斗云（QCA4019），一台华硕ACRH17（QCA9984+4019），一台竞斗云做主路由，再接交换机，然后接剩下两台（关DHCP）。
用的是lean的源码，编译的时候驱动都是不带后缀（例如ct，ct-htt等）的，应该都是开源驱动吧？比如ath10k-firmware-qca4019，kmod-ath10k等等。
或者说，这些的驱动也不支持？三台的Active node里都看不到彼此，设置是完全一样的。
先感谢大佬。
![图片](https://user-images.githubusercontent.com/47056935/141643783-dae06cda-1e90-414d-8319-8ee20ec17cba.png)

**Comment by ntlf9t** [comment]
用lean源码里的那个版本，这个由于dsa驱动问题脚本没写好

**Comment by stephensund** [comment]
> 
> 
> 用lean源码里的那个版本，这个由于dsa驱动问题脚本没写好

用的确实是lean仓库里的，不是我自己拉取的，所以觉得很奇怪

**Comment by stephensund** [comment]
我试试用这边最新的看看
