### ISSUE TITLE
关于是否需要 ap 模式的讨论

### ISSUE THREAD

**Issue by sotux** [ntlf9t/luci-app-easymesh#5]
在启动脚本中的 ap 模式相关代码，会修改 lan 口的 ip 地址、网关、dns、dhcp 等参数。
当用户启用 easymesh 并且不使用 ap 模式的情况下，脚本会删除 lan 口的这些参数，
但这个操作对用户是不透明的，若之后用户关闭了 easymesh，脚本只是给用户的 lan 口设置了一个自动参数。
对于自己设置过 lan 口固定 ip 和其它一些参数的用户来说，这不是一个好方法。

我认为 ap 模式可以不需要。若需要有线回程，用户可以自己设定 lan 口参数。
若用户不使用有线回程，则他可能连 lan 口的网线都没有接，即使设定了 lan 口的一些参数，也不影响 mesh 组网。

**Comment by ntlf9t** [comment]
怎么说呢，我最早写时候是没写ap模式的，不是所有用户都会关闭dhcp dhcpv6  firewall，写这个这个插件的初衷就是为了傻瓜式一站解决。
       想到的受众不同吧，比如我用直接改config就行了不要这个插件也行；比如你想这插件只要创建接口和无线就行了；当然还会有沙雕用户拿着别人编译好的固件，打开这个插件想着这玩意怎么用，他们的想法都是最好就只剩一个启动按钮。
       当然也可以分一个分支出来，主要没法解决启动easymesh 并且不使用 ap 模式的情况下的参数变动。

**Comment by ntlf9t** [comment]
已修复没问题就关了
