### ISSUE TITLE
luci-app-easymesh在lede的openwrt下打包失败

### ISSUE THREAD

**Issue by WYC-2020** [ntlf9t/luci-app-easymesh#7]
Collected errors:

check_conflicts_for: The following packages conflict with wpad-openssl:
check_conflicts_for: wpad *
opkg_install_cmd: Cannot install package wpad-openssl.
check_conflicts_for: The following packages conflict with wpad-openssl:
check_conflicts_for: wpad *
opkg_install_cmd: Cannot install package luci-app-easymesh.

初步看应该是wpad-openssl冲突导致，去掉wpad-openssl依赖后能编译成功通过

**Comment by swtatoyang** [comment]
wpad-openssl没有勾通，但也还是过不了

**Comment by swtatoyang** [comment]
> Collected errors:
> 
> check_conflicts_for: The following packages conflict with wpad-openssl:
> check_conflicts_for: wpad *
> opkg_install_cmd: Cannot install package wpad-openssl.
> check_conflicts_for: The following packages conflict with wpad-openssl:
> check_conflicts_for: wpad *
> opkg_install_cmd: Cannot install package luci-app-easymesh.
> 
> 初步看应该是wpad-openssl冲突导致，去掉wpad-openssl依赖后能编译成功通过

请问你是怎么去掉依赖的呢？

**Comment by RoweV194** [comment]
> > Collected errors:
> > check_conflicts_for: The following packages conflict with wpad-openssl:
> > check_conflicts_for: wpad *
> > opkg_install_cmd: Cannot install package wpad-openssl.
> > check_conflicts_for: The following packages conflict with wpad-openssl:
> > check_conflicts_for: wpad *
> > opkg_install_cmd: Cannot install package luci-app-easymesh.
> > 初步看应该是wpad-openssl冲突导致，去掉wpad-openssl依赖后能编译成功通过
> 
> 请问你是怎么去掉依赖的呢？

我是去掉wpad，有什么后果不知道。
在
-> Network 
 -> WirelessAPD
  -> wpad
里

**Comment by VergilGao** [comment]
这个包后续的维护貌似转入了 https://github.com/coolsnowwolf/luci
这个算是一个常见的问题了，就是 openssl 和 wolfssl 冲突的问题
